# playbooks/wp_core_version_export_onefile.yml
---
- name: Export WordPress core version per ISPConfig site into one CSV per host
  hosts: servers
  gather_facts: false
  become: true

  vars:
    export_base: "{{ lookup('env','HOME') }}/ansible-lab/export/version"
    clients_root: "/var/www/clients"
    web_dir_regex: "^/var/www/clients/client[^/]+/web[^/]+/web$"
    wp_bin: "wp"
    date_stamp: "{{ lookup('pipe', 'date +%F') }}"
    out_csv: "{{ export_base }}/{{ inventory_hostname }}.csv"

  tasks:
    # 1) Discover WordPress roots
    - name: Find directories up to depth 5 under {{ clients_root }}
      ansible.builtin.find:
        paths: "{{ clients_root }}"
        file_type: directory
        recurse: true
        depth: 5
      register: found_dirs

    - name: Filter only WordPress roots (…/clientX/webY/web)
      ansible.builtin.set_fact:
        web_dirs: >-
          {{
            found_dirs.files
            | selectattr('path', 'match', web_dir_regex)
            | map(attribute='path')
            | list
          }}

    - name: Fail if no WordPress web roots are found
      ansible.builtin.fail:
        msg: "No WP web roots matched {{ web_dir_regex }} under {{ clients_root }}"
      when: web_dirs | length == 0

    # 2) Identify site user from directory owner
    - name: Stat each web root to get owner (site user)
      ansible.builtin.stat:
        path: "{{ item }}"
        follow: true
      loop: "{{ web_dirs }}"
      loop_control:
        label: "{{ item }}"
      register: web_stats

    - name: Build sites list [{path, user, name}]
      ansible.builtin.set_fact:
        sites: "{{ sites | default([]) + [ {
          'path': item.item,
          'user': (item.stat.pw_name | default('root')),
          'name': (item.item | regex_replace('.*/(client[^/]+)/([^/]+)/web$', '\\1_\\2'))} ] }}"
      loop: "{{ web_stats.results }}"
      loop_control:
        label: "{{ item.item }}"

    # 3) Get domain (from wp option get home) => fname
    - name: Get primary site URL (home) for each WP root
      ansible.builtin.command:
        argv:
          - "{{ wp_bin }}"
          - option
          - get
          - home
          - "--path={{ item.path }}"
          - "--skip-plugins"
          - "--skip-themes"
      become_user: "{{ item.user }}"
      register: home_urls
      changed_when: false
      failed_when: false
      loop: "{{ sites }}"
      loop_control:
        label: "{{ item.name }} ({{ item.user }}) -> {{ item.path }}"

    - name: Merge domain filename (fname) into sites list (no inline comments)
      ansible.builtin.set_fact:
        sites_named: >-
          {{
            sites_named | default([]) + [
              item.0 | combine({
                'fname': (
                  (item.1.stdout | default('') | trim) != ''
                ) | ternary(
                    (item.1.stdout | default('') | trim
                     | regex_replace('^https?://', '')
                     | regex_replace('/.*$', '')
                     | regex_replace(':.*$', '')
                     | regex_replace('[^A-Za-z0-9._-]', '_')),
                    item.0.name
                  )
              })
            ]
          }}
      with_together:
        - "{{ sites }}"
        - "{{ home_urls.results }}"

    # 4) Ensure ONLY the base export folder exists on controller
    - name: Ensure base export folder exists on controller
      ansible.builtin.file:
        path: "{{ export_base }}"
        state: directory
        mode: "0755"
      delegate_to: localhost
      become: false

    # 5) Get wp core version per site
    - name: Get WordPress core version for each site
      ansible.builtin.command:
        argv:
          - "{{ wp_bin }}"
          - core
          - version
          - "--path={{ item.path }}"
      become_user: "{{ item.user }}"
      register: wp_core_versions
      changed_when: false
      failed_when: false
      loop: "{{ sites_named }}"
      loop_control:
        label: "{{ item.fname }} ({{ item.user }}) -> {{ item.path }}"

    # 6) Build CSV content with real newlines (render directly)
    - name: Prepare CSV string with header and rows
      ansible.builtin.set_fact:
        csv_content: |-
          host,site,path,version,date
          {% for r in wp_core_versions.results if r.rc == 0 %}
          {{ inventory_hostname }},{{ r.item.fname }},{{ r.item.path }},{{ (r.stdout | trim) }},{{ date_stamp }}
          {% endfor %}

    # 7) Write one CSV file per host to controller (overwrite each run)
    - name: Write aggregated CSV to controller
      ansible.builtin.copy:
        content: "{{ csv_content }}"
        dest: "{{ out_csv }}"
        mode: "0644"
      delegate_to: localhost
      become: false

    # 8) Optional: write error log if any failures
    - name: Write error log if any failures
      ansible.builtin.copy:
        content: |-
          Date: {{ date_stamp }}
          Host: {{ inventory_hostname }}
          {% for r in wp_core_versions.results if r.rc != 0 %}
          ---
          Site: {{ r.item.fname }}
          Path: {{ r.item.path }}
          User: {{ r.item.user }}
          RC: {{ r.rc }}
          STDOUT:
          {{ r.stdout }}
          STDERR:
          {{ r.stderr }}
          {% endfor %}
        dest: "{{ export_base }}/{{ inventory_hostname }}.ERRORS-{{ date_stamp }}.log"
        mode: "0644"
      when: (wp_core_versions.results | selectattr('rc','ne',0) | list | length) > 0
      delegate_to: localhost
      become: false

    # 9) Summary
    - name: Summary
      ansible.builtin.debug:
        msg: |-
          Wrote: {{ out_csv }}
          Sites OK: {{ (wp_core_versions.results | selectattr('rc','equalto',0) | list | length) }}
          Sites FAILED: {{ (wp_core_versions.results | selectattr('rc','ne',0) | list | length) }}
